services:
  - type: web
    name: Eingabe-Matching-Anzeigen  # Ändere dies, um den tatsächlichen Dienstnamen zu verwenden
    env: python
    region: frankfurt
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      ln -sf /usr/bin/tesseract /usr/local/bin/tesseract  # Stelle sicher, dass Tesseract korrekt verlinkt wird
      tesseract --version  # Überprüft, ob Tesseract korrekt installiert wurde
      pip install -r backend/requirements.txt
    startCommand: uvicorn backend.grundfunktion:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false


