services:
  - type: web
    name: Eingabe-Matching-Anzeigen
    env: python
    region: frankfurt
    buildCommand: |
      # Update the package list and install tesseract OCR
      apt-get update && apt-get install -y tesseract-ocr
      # Ensure that tesseract is linked correctly
      ln -sf /usr/bin/tesseract /usr/local/bin/tesseract
      # Check if tesseract is installed correctly
      tesseract --version
      # Install required python dependencies
      pip install -r backend/requirements.txt
    startCommand: uvicorn backend.grundfunktion:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false



